name: Deploy to Azure Container Apps

####
# MIT License
# 
# Copyright (c) Microsoft Corporation.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE
# 
# This GitHub Action requires the following secrets:
# AZURE_CREDENTIALS : a JSON payload allowing access to your Azure resources
# RESOURCE_GROUP_NAME : the name of the Azure resource group containing your Azure Container Apps instance
# CONTAINER_NAME : the name of your Azure Container Apps instance
# REGISTRY_URL : the URL of your container registry
# REGISTRY_USERNAME : the username of your container registry
# REGISTRY_PASSWORD : the password of your container registry
####

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build Spring Boot application with GraalVM
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.REGISTRY_URL }}/com.microsoft.samples.springopenai/spring-openai-bot:${{ github.sha }}
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker push to container registry
        run: |
          docker image push ${{ secrets.REGISTRY_URL }}/com.microsoft.samples.springopenai/spring-openai-bot:${{ github.sha }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ${{ secrets.CONTAINER_NAME }} -g ${{ secrets.RESOURCE_GROUP_NAME }} --image ${{ secrets.REGISTRY_URL }}/com.microsoft.samples.springopenai/spring-openai-bot:${{ github.sha }}
